# Слова, которые кот слушает
# Нужно как-то настроить обработку без регистра
listen_talk = '(кис|Кис|кц|Кц|Мур|мур|кс|Кс|Кот|кот|Мяу|мяу|Цап|Мяяяяяяяяяу|Мрррр|Няа|Мьяв|Миау|Мееееу|Мрррррррау!|Шшш|Миао|Мъяу|Мя|Мф|Мрмрмрмрмрмр|кусь|цап|хвать|жрать)'
listen_woof = '(гав|Гав)'

# Кот умеет говорить это:
talk = [
            'Мяу!',
            'Мяяяяяяяяяу',
            'Мрррр',
            '🐾🐾🐾',
            '💤',
            'Няа!',
            'Мьяв**',
            'Миау!!!',
            'Мееееу',
            'Мрррррррау!',
            'Мяу! Мяу! МЯУ!!!',
            'Шшшшшшшшшшшшшш',
            'Шшш...',
            'Жизнь тлен...',
            'Миао',
            'Мъяу',
            'Мя!',
            'Мяу мяу мяу мяу мяу мяу мяу',
            'Мф',
            '*ф* *ф* *ф*',
            'Мрмрмрмрмрмр',
            '*кусь*',
            '*цап*',
            '*хвать*',
            '*жрать*',
            'Мяу',
            'Ну допустим мяу'
            ]


voice = [
            'mew1.ogg',
            'mew2.ogg',
            'mew3.ogg',
            'mew4.ogg',
            'mew5.ogg',
            'mew6.ogg',
            'mew7.ogg',
            'mew8.ogg',
            'mew9.ogg',
            'mew10.ogg',
            'mew11.ogg',
            'mew12.ogg',
            'mew13.ogg',
            'mew14.ogg',
            'mew15.ogg',
            'mew16.ogg',
            'mew17.ogg',
            'mew18.ogg',
            'mew19.ogg',
            'mew20.ogg',
            'mew21.ogg',
            'mew22.ogg',
            'mew23.ogg',
            'mew24.ogg',
            'mew25.ogg',
            'mew26.ogg',
            'mew27.ogg',
            'mew28.ogg',
            'mew29.ogg',
            'mew30.ogg',
            'mew31.ogg',
            'mew32.ogg',
            'mew33.ogg',
            'mew34.ogg',
            'mew35.ogg',
            'mew36.ogg',
            'mew37.ogg',
            'mew38.ogg',
            'mew39.ogg',
            'mew40.ogg',
            'mew41.ogg',
            'mew42.ogg',
            'mew43.ogg',
            'mew44.ogg',
            'mew45.ogg',
            'mew46.ogg',
            'mew47.ogg',
            'mew48.ogg',
            'mew49.ogg'
            ]

shh = [
            'mew49.ogg',
            'mew14.ogg',
            'mew48.ogg',
            'mew15.ogg',
            'mew47.ogg',
            'mew13.ogg',
            'mew40.ogg',
            'mew41.ogg',
            'mew42.ogg',
            'mew43.ogg',
            'mew16.ogg'
            ]


sticker = [
            'CAACAgEAAxkBAAEEih5iYw04LuTSvdpNTRmPitiw8pPAMQACRQ8AAtkRQUdD8HMvdvRwJiQE',
            'CAACAgEAAxkBAAEEihhiYw0pMU79AAFgER7x60AGD-3Wb8UAAowBAAIUbEFHPTGpMzqR3-skBA',
            'CAACAgEAAxkBAAEEihpiYw0uJZKPuplcQ4besfQOmAPV1gAC8AADTxg5R5zz_FLIZN2PJAQ',
            'CAACAgEAAxkBAAEEihxiYw00-Wlip-UCiBdiPhiBfrT0HwACpQMAAlHhiUd3_q0oUA2S2SQE',
            'CAACAgEAAxkBAAEEihZiYw0nQVPAGnFKUamjtYPoWESO_AACXgEAAsOyQEcTfOmsRkaQAAEkBA',
            'CAACAgEAAxkBAAEEiiBiYw1WMyujlfu_0Xj-ZbuPLW9-8wACEQEAAqWqwUZhR5fHQwZtgyQE',
            'CAACAgEAAxkBAAEEiihiYw1ka-uShHljVQrUqF2VJ6TAsAACqQIAAiOm-EU1cE5ggtmFWiQE',
            'CAACAgEAAxkBAAEEiiJiYw1ZQTRAfj9SYxTm0VaSZR7KQQAChQEAAv3myEYCLsW_s1YmuiQE',
            'CAACAgEAAxkBAAEEiipiYw1tZ-LqtdxT7u5vVzY7Mg6_dAACSwIAAgSUyUZr45LI3SpvpSQE',
            'CAACAgEAAxkBAAEEiiRiYw1bHoACpXjmUYf770S2VDcpHAACEQMAAul-8UVYtT9UWMyWHyQE',
            'CAACAgEAAxkBAAEEiiZiYw1eO0G7atsRLhHPjBOgIwvCqgACagIAArT3-UX4xht0knUsRyQE',
            'CAACAgIAAxkBAAEEic5iYwy1tXq3s3M5CBvf_wHRRUm3BAAC7xMAAoZm6UvEin4sHy46NCQE',
            'CAACAgIAAxkBAAEEichiYwyrYm4WXFObE52CivCYZA4WiwAC9w4AAoog6Uu2fTdggHh8oSQE',
            'CAACAgIAAxkBAAEEicJiYwykrw1nli9b73-7_zb6p-ddpwACjBQAApA86Uu-p57-IBrgbyQE',
            'CAACAgIAAxkBAAEEicpiYwyvqUBxQYZDehbi070YMxGnDQAC3g4AArm86EsSHYXPT5fQmSQE',
            'CAACAgIAAxkBAAEEicRiYwyn4Fxih6_IFb8fd0vVuS7sXQAC7RMAAgQm6Uv32TwLK8JzkiQE',
            'CAACAgIAAxkBAAEEicxiYwyz-cHa6jRbW_1BpmPh529WEgAC9A0AApK26EtRpMEU4xg3eyQE',
            'CAACAgIAAxkBAAEEicZiYwypYKMGHlYSXM9SxvB1mbGhdwACZhQAAhPw4EvGpRrGfVocVCQE',
            'CAACAgIAAxkBAAEEid5iYwzED3BS1GallhLDl70CW0k-xAACAhAAAhTR6EvYkWdNoTM-tiQE',
            'CAACAgIAAxkBAAEEidBiYwy2Ge2JEouDOwpBQmGoXmMn2AACtQ4AApPe6UtyZ-hIVloUBSQE',
            'CAACAgIAAxkBAAEEidhiYwy_MuCoTwABUlKwXJQTrUzpjpgAAowQAAI8EOlL2qen2esPyp0kBA',
            'CAACAgIAAxkBAAEEidJiYwy6loRjsiKyVje2hyZM9AyHwwACyxEAAjKG6EuOrNdm-jNN_yQE',
            'CAACAgIAAxkBAAEEidpiYwzB6jtlzGIIsFZg8MJ-HXmggQACsxAAAl-r6Ev-8ucd_oqRJiQE',
            'CAACAgIAAxkBAAEEidRiYwy86Cm632MRJRroPZPyssxFagAC6RgAAjbm4EvkiC5eRMaCDyQE',
            'CAACAgIAAxkBAAEEidxiYwzDpETKc-04F7ULCSGlq9Lp1QACUA8AAqZI6Uul8NDsaP8iRCQE',
            'CAACAgIAAxkBAAEEidZiYwy-94bDlbZXdMK2a-Z5enu9PQACjA8AAs5o6EsZu8phvAGUyCQE',
            'CAACAgIAAxkBAAEEie5iYwzSUkN7IGR9AYsg8fVn6QPMMgACqhIAAk-d6EvRqDzggKWF_iQE',
            'CAACAgIAAxkBAAEEieBiYwzHIM_3z1eeKOnGB9gf__TyygAC_w8AAnzA6Uu6ty10FffVciQE',
            'CAACAgIAAxkBAAEEiehiYwzN0SVJrRDyVtLfGlnZFr18PwACUg4AAqrJ6Et_AAHN_RuZmEYkBA',
            'CAACAgIAAxkBAAEEieJiYwzI39ij6TLeFsIhDHawYwh-KAACzw0AAhFd6UuAkrr0-ZD7JCQE',
            'CAACAgIAAxkBAAEEiepiYwzPSsLPyzrSDd67F7XgTCkLawACYA4AAgOJ6EuL2ZPwAf-wzyQE',
            'CAACAgIAAxkBAAEEieRiYwzKZvjgghG0pc7P0a31o5nvbQACAQ4AAi8E6EtKZdbxU1KvoyQE',
            'CAACAgIAAxkBAAEEiexiYwzRk8t3cwetiN7_PF0C8dlhiQAC7BIAAotK6Evc1acao5l9mSQE',
            'CAACAgIAAxkBAAEEieZiYwzMDk8fUtPZL8maDfQevF0xDAACUBEAAqo56EtfpJnyUhkc3iQE',
            'CAACAgIAAxkBAAEEif5iYwzoXgvNIyDOnwZpWWCUFlikAwAChgADXAxyG4n3MoGTaRHmJAQ',
            'CAACAgIAAxkBAAEEifBiYwzU-ldOuRhLT2n3racsvQ1SYwACiRIAAoJx6Utt8WxKWD8tryQE',
            'CAACAgIAAxkBAAEEifdiYwzf_FhjozLguukvgLsZH5jZ5wACggADXAxyG46VP_DLetvhJAQ',
            'CAACAgIAAxkBAAEEifJiYwzWlda6SJzz7-q3xb7COB0w0AACVg8AAuGK6UtVg9mbYu9KFyQE',
            'CAACAgIAAxkBAAEEifpiYwzigqrLyfo55nuSwJu9gcQXBwACgwADXAxyGzyyQXApSEZdJAQ',
            'CAACAgIAAxkBAAEEifRiYwzct3b_ycjkJwOCeQ-iAuBfqwACgAADXAxyG0pJpsfWDngaJAQ',
            'CAACAgIAAxkBAAEEifxiYwzm4BCuS12aNHvbf6jaEtdRIQAChQADXAxyG5hLSFlFCvYwJAQ',
            'CAACAgIAAxkBAAEEifZiYwzedXYm72iLHdT_RDlVuV0K1gACgQADXAxyG9RSX6dJZJ4MJAQ',
            'CAACAgIAAxkBAAEEig5iYw0RK2RNrMvapz4lcHGBnwzXzwACrgADXAxyG_1QRfnGUm1rJAQ',
            'CAACAgIAAxkBAAEEigABYmMM6md4nvx84BjfLQrRlJXmhgMAAocAA1wMchu0Op1zjao7qCQE',
            'CAACAgIAAxkBAAEEighiYw0EShY-lMwMu8GtWrbixBlkJwACmwADXAxyGyozmLlN-jaCJAQ',
            'CAACAgIAAxkBAAEEigJiYwz09HrVoa-J1MRTket9ITs2awACjgADXAxyGxANveHeo9zQJAQ',
            'CAACAgIAAxkBAAEEigliYw0Fa_1y8uFOUILpA3Nfa5hl4QACnAADXAxyG4H4hy1cNHHgJAQ',
            'CAACAgIAAxkBAAEEigRiYwz6sBKkBipbDe_gbkWr0L6qMQACkgADXAxyGw-JkBqikVryJAQ',
            'CAACAgIAAxkBAAEEigxiYw0Lk4MgZSPRuSk6JcOd8D0bBAACnwADXAxyG1-Mxk5pGLMtJAQ',
            'CAACAgIAAxkBAAEEigZiYw0BTK0cn6hMKTjtNr9dsNXwPQAClwADXAxyG6yZdd2S9itLJAQ',
            'CAACAgIAAxkBAAEEihBiYw0VfUbriZoW-FxS6Jg8Xn7atwACtwADXAxyGy2HY3JGl7c6JAQ',
            'CAACAgIAAxkBAAEEihJiYw0WbjPOi2pfUNGT3IVPLI25jwACugADXAxyGx-N5BdELWGlJAQ',
            'CAACAgIAAxkBAAEEihRiYw0cuBU0Zh_sWEsgldgbqlIoxwACwQADXAxyGwbk5JYCS0aEJAQ',
            'CAACAgIAAxkBAAEEii5iYw2jSPQzPVRrMyPYC2A2IHG_TgACfE8CAAFji0YMhz51swV0K4IkBA',
            'CAACAgIAAxkBAAEEiixiYw1-3vWnKQLe0TGzzG1180qHPQAChk8CAAFji0YMjSd2VWGt1LckBA',
            'CAACAgIAAxkBAAEEij5iYw3MKZJs4JYsNjiYnEA_fIu52gACnBMAAu7QiEpOut3zm1RTdyQE',
            'CAACAgIAAxkBAAEEijBiYw2oLEmAOU_MNYEXFv6eY61H3QACTxUAAvgn0UlTfZceecmEzSQE',
            'CAACAgIAAxkBAAEEijhiYw21woWQoxmRwotzQVqE3ZaaSwAClBUAAupJ0Emy-_AINDNgMiQE',
            'CAACAgIAAxkBAAEEijJiYw2qB3jLfCSaCfxlycvhD3AOqwACGhEAAnw50UlvjxMse99CYyQE',
            'CAACAgIAAxkBAAEEijpiYw22KLir-ftNfTIZBevIazF8fAACwxEAAgQH0Elj1cTD65pA9CQE',
            'CAACAgIAAxkBAAEEijRiYw2sa8rPMdLErwJaHnDNKzYe_wACYhMAAhrY0EnB37V5h6tCSSQE',
            'CAACAgIAAxkBAAEEijxiYw3K0ny-Ij3VbTrrpVnRjSFprwACThUAAvPYiErbccQRWw3YbiQE',
            'CAACAgIAAxkBAAEEijZiYw2z0i61Un6fN5FO21WMjHHzpgACyBMAAkeW2UnPmBoUjC4QpSQE',
            'CAACAgIAAxkBAAEEik5iYw3eGjUflhB0ikHXh8TbWY5VDwACfxQAAtxg2UtpIGY9LiTelCQE',
            'CAACAgIAAxkBAAEEikBiYw3O8EhIE3ZoA_vB2qvlbJ-PngACIRcAAoe4kUrUWP9nTmybCyQE',
            'CAACAgIAAxkBAAEEikhiYw3ZF2rlmh2qW8z7gi4-O-1zRgACkBMAAjCloUrZ88113EXNBSQE',
            'CAACAgIAAxkBAAEEikJiYw3QHWshbYdVXL6ZkQZvxH49swACDREAAs3amEoI7VMGrByieyQE',
            'CAACAgIAAxkBAAEEikpiYw3beySfSaCeroXsHekpMH16UQAClxUAAoYg0UvzsP_-T4JBLiQE',
            'CAACAgIAAxkBAAEEikRiYw3U33n6kOiRvrqo9tdKLjzjngAC6xMAAlUDqEr9BOZ1wPaT0iQE',
            'CAACAgIAAxkBAAEEikxiYw3cRF0C9Xph4bN4GpcEYtS4WwACBRMAAjVh0UutcFo5hJDGZiQE',
            'CAACAgIAAxkBAAEEikZiYw3W8ow5r3mO_MNJT3K3RAg0EQACnxQAAvHFoUoVzgk7SvkyhSQE',
            'CAACAgIAAxkBAAEEil5iYw30hSi6ChMKusXGgX5JtlcrRQACow0AAsVHEEsNLyaEeI7FXSQE',
            'CAACAgIAAxkBAAEEilBiYw3gFutT5hi8pxcG5_F8naxQbQACgBwAAg80IUmk4Yjv7vGH5SQE',
            'CAACAgIAAxkBAAEEilhiYw3p_2v-h1bAaMRZnG6Jl7wHaAACv6IBAAFji0YMPN03pInLaAwkBA',
            'CAACAgIAAxkBAAEEilJiYw3iNevGF0IjHmvh3_0PRkVCaAACexIAAo440UuDH_jueMmsPSQE',
            'CAACAgIAAxkBAAEEilpiYw3uiCBJBUHIyW4SsFTQS7dczgACyKIBAAFji0YMK9hJAmAlnQokBA',
            'CAACAgIAAxkBAAEEilRiYw3jEnNPyuyyubuGlYTFGezH9gACtBoAAh1WKUnUjzTa4JmbrCQE',
            'CAACAgIAAxkBAAEEilxiYw3yopHgRaLzfz7-srGVwvkCAwAC-w4AAiOsEEtttYrrHw_zsSQE',
            'CAACAgIAAxkBAAEEilZiYw3lP8uOlSjlrSfHzX19Eez7rAACoREAAlXtoEqfu9tldJGDciQE',
            'CAACAgIAAxkBAAEEimBiYw326Cz2T7QQLVkT2rK_n5LbSgACGAwAAoVTCUuZAAGg0q5AoNEkBA',
            'CAACAgIAAxkBAAEEimhiYw4BJiybAAHS6RKBNNSusv4_Lz4AAlYPAAIk2RFLr7xkPAqEGTQkBA',
            'CAACAgIAAxkBAAEEimJiYw34XdgyX3Qhe5pWx8_fjHue0gACbg4AAsc4EUsKogfD4F6q-CQE',
            'CAACAgIAAxkBAAEEimRiYw3620JHiPQbgCykoOwGSM2EIAACGw4AAqJPEEs6IWtEkvp8gyQE',
            'CAACAgIAAxkBAAEEimZiYw3_ZKDiS_qLyyX_gB_h9egikAACJQwAAhIjCUvcwTF6fxw-iyQE',
            'CAACAgIAAxkBAAEEin5iYw5Ezi72KUmJri6sgeqTY30WrgACFK0BAAFji0YM_gIw7VP5mP8kBA',
            'CAACAgIAAxkBAAEEioBiYw5G_eOuJLGn5eagfXEXloaqAwACFa0BAAFji0YMy-fKUlvqmHokBA',
            'CAACAgIAAxkBAAEEiohiYw5MbF7Uv0Fyj5xFduXg3VyEfgACGa0BAAFji0YMFCE_77nb_-8kBA',
            'CAACAgIAAxkBAAEEioJiYw5H357URxCQUZFJ01qTU83BYwACFq0BAAFji0YMXwIM-A0OT2UkBA',
            'CAACAgIAAxkBAAEEioRiYw5JgA97-LLy9zdWus2NzALYMwACF60BAAFji0YMt-RxsOFOefwkBA',
            'CAACAgIAAxkBAAEEioZiYw5Lx2FKtmt9skLAoPWhVgYdsgACGK0BAAFji0YMeGT4tYCNO9okBA',
            'CAACAgQAAxkBAAEEim5iYw4d-uMjCqyzlkXmBjLroaXdlwACmwkAAtMHuFJ1C-KiSKLSGyQE',
            'CAACAgQAAxkBAAEEimpiYw4banWu4-EepSCTv4xb8HVjhgACyAsAAkRp8FAxH1ebosbOaCQE',
            'CAACAgQAAxkBAAEEimxiYw4c-bnNzwaO36-sUH4ECDvtQQACbRUAAkJZ_QTyC4pdRpTPTyQE',
            'CAACAgQAAxkBAAEEinBiYw4jrO8MY86e8nxZssifvKWuSAAC-QsAAnHxUVNfp-Q0XVh7RSQE',
            'CAACAgQAAxkBAAEEinhiYw45-y9R0X0mr9p2mzjz7PxXTQACxQoAAkj_oFM43uYAAbGuiUMkBA',
            'CAACAgQAAxkBAAEEinJiYw4lmEySW2jEpoBGP2idvukaVQACcQsAAo9SSVFFVmZZbQ1DPiQE',
            'CAACAgQAAxkBAAEEinpiYw48TTgScuop5vslSClQ7_KoJgACzRUAAkJZ_QQJ3ZEPo0FsiiQE',
            'CAACAgQAAxkBAAEEinRiYw4wWKXw16VEwdhP1uk4CUHOzgACFgsAAowroVMUqbCKqWMUTSQE',
            'CAACAgQAAxkBAAEEinxiYw5A6kJkxoPg1moMAxeHrmDxyQACzAkAAk-tiFBazDYsz70mmCQE',
            'CAACAgQAAxkBAAEEinZiYw4yIK23gY-heKoaXHsxdP36RAACqgsAAt_piFHhNwot1ddG_SQE'
            ]
